### ISSUE TITLE
asset url issue

### ISSUE THREAD

**Issue by brandonneil** [ITS-UofIowa/uiowa_favicon#2]
Tippie is reporting urls like http://test.sitenow.uiowa.edu/tippie/future-graduate-students/mba-programs/sites/all/modules/custom/uiowa_favicon/assets/favicon-16x16.png for assets which are failing. 

I think this is related to https://github.com/ITS-UofIowa/uiowa_favicon/blob/7.x-1.x/uiowa_favicon.module#L8 - we need to add $GLOBALS['base_path'] (I think) so it loads correctly.

**Comment by adamdelaney** [comment]
This issue should be resolved with commit: 4a08799f85c3aa27b4b14634d7acaeebed50d1f6
